### ISSUE TITLE
SSPlex back-end doesn't support mixed case of any sort.

### ISSUE THREAD

**Issue by JamminR** [mikew/ss-plex.bundle#24]
SSPlex doesn't 'find' any search term if it has capital letters in it.
Though the results 'returned' from a search of lower case show mixed/Title case, trying to find any item with Title/mixed case results in 'no matches'.
This was tested and confirmed in both PlexWeb and Roku Plex clients.
See SPlex forum conversation at/before/near this for more discussion - http://forums.plexapp.com/index.php/topic/48412-rel-ss-plex/?view=findpost&p=482660

Quick example - Enter SSplex, search for "American Horror" - No results.
Search for "american horror" - finds several, including some mixed case themselves.

**Comment by mikew** [comment]
apologies for taking so long to get this fixed.
