### ISSUE TITLE
stuck in fav/un-fav loop on Roku 3

### ISSUE THREAD

**Issue by ahmadnassri** [mikew/ss-plex.bundle#25]
when accessing ss-plex through Roku's Plex channel, I'm able to navigate to the show level, then upon clicking the show, the interface gets stuck in a "add to favourite" / "remove from favourite" loop.

**Comment by ahmadnassri** [comment]
@mikew i'm not seeing any fixes / commits? was this fixed?

**Comment by mikew** [comment]
I'll need to see logs from your server and the channel, but without access to a roku I'm unable to really debug the issue.

will reopen if this is still an issue with everything up to date
