### ISSUE TITLE
Dissapeared from Plex and update says No Longer Supported

### ISSUE THREAD

**Issue by crhatfield** [mikew/ss-plex.bundle#30]
Upgraded Plex last night since SS Plex hasn't been loading for me and afterwards I find that SS Plex is missing, So I go into Unsupported Appstore and update manually and get the message "SS Plex : No longer supported. No updates."

**Comment by gddeen** [comment]
Move the ss-plex bundle directly into the directory where all of the other bundles are stored.
Application Support/Plex Media Server/Plug-ins

ss updates itself from github.

The original bundle is found on github also.

Is that clear enough? Do you want more detail?

**Comment by crhatfield** [comment]
I'll give it a try when I get home. Thank you.

On Friday, April 18, 2014, gddeen notifications@github.com wrote:

> Move the ss-plex bundle directly into the directory where all of the other
> bundles are stored.
> Application Support/Plex Media Server/Plug-ins
> 
> ss updates itself from github.
> 
> The original bundle is found on github also.
> 
> Is that clear enough? Do you want more detail?
> 
> On Apr 18, 2014, at 9:15 AM, crhatfield <notifications@github.com<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > Upgraded Plex last night since SS Plex hasn't been loading for me and
> > afterwards I find that SS Plex is missing, So I go into Unsupported
> > Appstore and update manually and get the message "SS Plex : No longer
> > supported. No updates."
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mikew/ss-plex.bundle/issues/30#issuecomment-40815102
> .

## 

Thank you,
- Cecil

# 

_Cecil R. Hatfield Jr._
Owner / Technician / Developer
_Hatfield Technology_

_"I.T. Services & I.P. Development"_
_(402) 630-4935HatfieldTechnology@GMail.com_

_https://www.facebook.com/HatfieldTechnology
https://www.facebook.com/HatfieldTechnologyhttps://www.twitter.com/HatfieldTech
https://www.twitter.com/HatfieldTech_

# _Skype ID: crhatfield_

http://www.zend.com/store/education/certification/authenticate.php?ClientCandidateID=ZEND901125&RegistrationID=0502004
  http://www.linkedin.com/pub/cecil-hatfield/46/1a5/561

**Comment by mikew** [comment]
Hmmm, to be honest I haven't really used the UAS in a while just go with the zip linked in the readme.

Has there been any progress with your issue?

**Comment by crhatfield** [comment]
Thanks Mike, yeah I deleted out the UAS copy and downloaded from the repo and presto, it worked again. Thanks for all you do man!
