### ISSUE TITLE
Enhancement Request: Use aria2 as an alternative to curl and wget

### ISSUE THREAD

**Issue by hermanjustnu** [mikew/ss-plex.bundle#35]
From http://aria2.sourceforge.net/:

"aria2 is a lightweight multi-protocol & multi-source command-line download utility. It supports HTTP/HTTPS, FTP, BitTorrent and Metalink. [...] [S]ource distribution and binaries [are available] for OS X, Windows and Android."

"Features
- Multi-Connection Download. aria2 can download a file from multiple sources/protocols and tries to utilize your maximum download bandwidth. Really speeds up your download experience.
- Lightweight. aria2 doesn’t require much memory and CPU time. When disk cache is off, the physical memory usage is typically 4MiB (normal HTTP/FTP downloads) to 9MiB (BitTorrent downloads). CPU usage in BitTorrent with download speed of 2.8MiB/sec is around 6%.
- Fully Featured BitTorrent Client. All features you want in BitTorrent client are available: DHT, PEX, Encryption, Magnet URI, Web-Seeding, Selective Downloads, Local Peer Discovery and UDP tracker.
- Metalink Enabled. aria2 supports The Metalink Download Description Format (aka Metalink v4), Metalink version 3 and Metalink/HTTP. Metalink offers the file verification, HTTP/FTP/BitTorrent integration and the various configurations for language, location, OS, etc.
- Remote Control. aria2 supports RPC interface to control the aria2 process. The supported interfaces are JSON-RPC (over HTTP and WebSocket) and XML-RPC."

**Comment by Krule** [comment]
:+1:

**Comment by mikew** [comment]
keep in mind the downloads are a lowest-common-denominator situation, as in, anything that wget or curl don't support won't be used.

the multi-connection stuff would be great to have.
