### ISSUE TITLE
Search doesn't find Manhatten

### ISSUE THREAD

**Issue by kurtman1111** [mikew/ss-plex.bundle#36]
The search function can't find the TV Series Manhattan but if I download from another source and put them into the TVShows folder it pulls all the metadata and works fine. Is there any way to manually insert this into Favorites?

**Comment by mikew** [comment]
![screen shot 2015-01-13 at 1 38 31 pm](https://cloud.githubusercontent.com/assets/4729/5725479/860f7cb6-9b29-11e4-8407-2bb1c59cf5a6.png)

closing since it was not hard to find
