### ISSUE TITLE
Most new shows not parsed since 9-28

### ISSUE THREAD

**Issue by Managrmny** [mikew/ss-plex.bundle#37]
Props to you for the best Plex app ever, I haven't loved anything this much since my first child was born... That being said, since 9-28 there are very few new episodes of any shows being found. I was wondering if that magic server of yours needs a reboot or if something else is wrong.

Thanks for all your hard work.

**Comment by mikew** [comment]
Working on a new metadata provider, since nothing is getting proper air
dates, noting new will show up in the recently released sections.
- Mike Wyatt

**Comment by crhatfield** [comment]
yeah I'm having the same issue.. fingers crossed you find a new metadata provider..dont know if it helps but the app "Let Me Watch This" in the Unofficial App Store has new shows; they just dont have the awesome Watch Later feature like yours (even though they have a semi-hidden link that says that; it doesn't work) - you might be able to use the same meta data provider they use (_shrug_)

**Comment by mikew** [comment]
I made the switch to a new metadata provider last night, we'll see how it performs over the next few days.

At least new items will appear in your favorites again.

## 

Mike Wyatt
+1 (709) 749-3575

**Comment by mikew** [comment]
closing since things have been stable for a while
