### ISSUE TITLE
Ambiguous file names 

### ISSUE THREAD

**Issue by crhatfield** [mikew/ss-plex.bundle#38]
Hello,

Since an update awhile back, when the meta data provider got changed (assuming), the file names have been saving differently, like 'Dr Who 2005' series is now saving as just Dr Who and so the images and meta data downloading for the shows are showing the original Dr Who instead of the 2005 reboot. Another is The Flash 2014, in both cases I just rename the files with the appropriate year in the name and refresh Plex and it fixes the problem for the most part (unless I have viewed the title already, then image & meta data of original series gets cached, otherwise its fine). Not really anything to lose sleep over however, shows still play just fine, just wanted to mention this one anomaly I noticed.

**Comment by mikew** [comment]
this means the meta data provider changed the names of the shows on their end from `The Flash (2014)` to `The Flash`

it's annoying for sure, but closing because it's out of the channel's hands
