### ISSUE TITLE
Add to Favourites not working

### ISSUE THREAD

**Issue by robdberlin** [mikew/ss-plex.bundle#42]
Am experiencing an issue when adding TV shows to favourites from search results. Instead of getting the confirmation dialogue "(name of tv show) has been added to your favourites" I get the opposite "(name of tv show) has been removed from favourites".

Same happens when I try and save searches. I get the "removed" dialogue instead of the saved dialogue. When I try and remove my favourites, or saved searches, the opposite happens and I get the "added" dialogue.

I've deleted and reinstalled the plugin and reset it from within Plex. Neither has fixed the issue.

**Comment by mikew** [comment]
Are you on a Roku by chance?

**Comment by robdberlin** [comment]
Nope. Running Plex Media server from an iMac on Yosemite 10.10.2. Connecting remotely using a MacBook Air running Plex Media Player, also running Yosemite 10.10.2.

**Comment by Kmagn13** [comment]
Notice Server is down? nothing loads and get a "whoops" on the main screen of SS-Plex

**Comment by mikew** [comment]
thanks for the heads up, the issue has been resolved.
