### ISSUE TITLE
FreeNAS Plex pbi plug-in support?

### ISSUE THREAD

**Issue by Drab-Crab** [mikew/ss-plex.bundle#48]
I am a fan of your plugin and am curious of the possibility of porting it to the FreeNAS pbi installation of Plex?  Within the FreeNAS GUI, you can download a plug-in and it will automatically create the jail and configure it for you, however, it creates a much different application path and library paths than the stand alone instance.

I have been looking at your code and wonder if it would be be a matter of creating a "FreeNAS-run.sh" file or would there need to be a serious rewrite to make it work.  I am not a fun of unnecessary forks for small changes.

Thanks

**Comment by mikew** [comment]
Hm, I'm really not sure how Plex channels work on NAS.

The cache system expects to have disk access (but uses relative paths), and the download feature requires curl or wget. Everything else is Python and the Plex channel API.

**Comment by Drab-Crab** [comment]
Relatively speaking, NAS Plex works just like a linux installation.  You can actually fully build a Plex instance inside of a FreeNAS jail and add your ss-Plex plugin without incident.  However, FreeNAS in particular has a premade plugin PBI (Push button installer) that creates the jail, installs files, configures services and the like for you, all you need to do is link media storage.  The biggest difference I am noticing is that in your "run-ubuntu.sh" script, you are exporting relative paths that do not exist in the Plex PBI jail.  All of the resources you are exporting in that script exist, just not in the paths you have entered.

**Comment by mikew** [comment]
Those scripts are only for running tests locally without a Plex server running, they are not touched on a regular install.
