### ISSUE TITLE
sorry  

### ISSUE THREAD

**Issue by chocolatesuper** [mikew/ss-plex.bundle#62]
<img width="1440" alt="captura de pantalla 2016-12-01 a las 16 02 23" src="https://cloud.githubusercontent.com/assets/22038180/20812634/49488bb2-b7e0-11e6-93b7-87a589348f86.png">
<img width="1440" alt="captura de pantalla 2016-12-01 a las 15 46 59" src="https://cloud.githubusercontent.com/assets/22038180/20812658/5d7653a8-b7e0-11e6-970c-0e32b7827760.png">

help me version 1.1.0 updates freind thank you api pocpon resolve

**Comment by mikew** [comment]
Closing since this has nothing to do with this project
