### ISSUE TITLE
Save for later not working for me..

### ISSUE THREAD

**Issue by schieving** [mikew/ss-plex.bundle#67]
I read recently that some of these issues are closed but I just updated to plex 1.5.6.3790 and I have also updated to the latest ss-plex.bundle and I have reset sources and cache and everything and still all my download/watch later fail. 

I am able to watch some of the things I look up immediately however some of them fail after about 5 mins, could be the connection, but my save for later just fails almost immediately. I have completely uninstalled and reinstalled both Plex and ss-Plex. On a Mac if that matters.

Anyone?

**Comment by mikew** [comment]
See [Nothing will download, what do I do?](https://github.com/mikew/ss-plex.bundle#q-nothing-will-download-what-do-i-do)

**Comment by schieving** [comment]
Reset everything a second time and things are working now. Not sure what has/had changed but thanks!
