### ISSUE TITLE
notify of new episodes in favorites

### ISSUE THREAD

**Issue by mikew** [mikew/ss-plex.bundle#7]
would be great if shows in the favorite list could also let you know if there is a new episode. something as simple as:

Archer
* Bob's Burgers
The Walking Dead

**Comment by slm4996** [comment]
This is a great idea, maybe take it a step further and allow the user to set "automatically watch later" for favorites?

**Comment by mikew** [comment]
Exactly what I was thinking. Also, this was added in the 1.0.0 release, so I will close the issue. Feel free to create an issue for your enhancement to track any future progress.
